"""Tests for the .kdimg container parser (kdimage.py).

Images are generated by helpers.kdimg_builder rather than shipped as binary
fixtures, so every offset and size asserted here is one the test itself chose.
"""

import hashlib

import pytest
from helpers.kdimg_builder import Partition, build_kdimg, write_kdimg_file

from k230_flash.kdimage import KburnKdImage, KdimageError, get_kdimage_items, get_kdimage_max_offset


@pytest.fixture
def two_partitions():
    return [
        Partition("uboot_spl_a", offset=0x000000, data=b"\xa5" * 512),
        Partition("uboot_a", offset=0x100000, data=b"\x5a" * 1024),
    ]


@pytest.mark.parametrize("version", [1, 2])
def test_parses_partition_table(tmp_path, two_partitions, version):
    """Both table layouts parse, and the values survive the round trip.

    V1 stores part_flag as uint32 and V2 as uint64 with padding, so a struct
    mistake in either shows up as garbled offsets rather than a clean error.
    """
    img = write_kdimg_file(tmp_path / f"v{version}.kdimg", two_partitions, version=version)

    items = get_kdimage_items(img)

    assert items is not None
    assert items.size() == 2
    first, second = items.data
    assert first.partName == "uboot_spl_a"
    assert first.partOffset == 0x000000
    assert first.partSize == 512
    assert second.partName == "uboot_a"
    assert second.partOffset == 0x100000
    assert second.partSize == 1024


def test_parsing_a_second_image_does_not_return_the_first(tmp_path):
    """The parser used to be a singleton keyed on nothing at all, so the second
    call handed back the first file's parse -- with the first file's partition
    names, offsets and content offsets.

    Deliberately no reset fixture: the point is that back-to-back calls in one
    process are correct on their own. The GUI populates its partition list this
    way per selected file, and a batch flash writes several images per process,
    so the stale parse meant flashing the wrong contents entirely.
    """
    first = write_kdimg_file(tmp_path / "first.kdimg", [Partition("uboot_a", offset=0x0, data=b"\x11" * 512)])
    second = write_kdimg_file(tmp_path / "second.kdimg", [Partition("rootfs_b", offset=0x100000, data=b"\x22" * 1024)])

    assert [i.partName for i in get_kdimage_items(first).data] == ["uboot_a"]
    assert [i.partName for i in get_kdimage_items(second).data] == ["rootfs_b"]
    # And back again -- a cache that only ever filled once would pass the above
    # by luck if the order happened to suit it.
    assert [i.partName for i in get_kdimage_items(first).data] == ["uboot_a"]


def test_max_offset_follows_the_image_it_was_asked_about(tmp_path):
    """Same singleton bug, via the other entry point: the capacity check read
    whichever image was parsed first."""
    small = write_kdimg_file(
        tmp_path / "small.kdimg", [Partition("a", offset=0, data=b"\x00" * 16, size=16, max_size=0x1000)]
    )
    large = write_kdimg_file(
        tmp_path / "large.kdimg", [Partition("b", offset=0, data=b"\x00" * 16, size=16, max_size=0x800000)]
    )

    assert get_kdimage_max_offset(small) == 0x1000
    assert get_kdimage_max_offset(large) == 0x800000


def test_items_are_sorted_by_offset(tmp_path):
    """write_kdimg walks items in order, so the parser must sort by offset even
    when the table lists partitions out of order."""
    out_of_order = [
        Partition("second", offset=0x200000, data=b"\x22" * 256),
        Partition("first", offset=0x000000, data=b"\x11" * 256),
    ]
    img = write_kdimg_file(tmp_path / "unsorted.kdimg", out_of_order)

    items = get_kdimage_items(img)

    assert [i.partName for i in items.data] == ["first", "second"]


def test_read_part_data_returns_payload(tmp_path, two_partitions):
    img = write_kdimg_file(tmp_path / "ok.kdimg", two_partitions)
    kdimg = KburnKdImage(img)
    items = kdimg.items()

    data = kdimg.read_part_data(items.data[0])

    assert data == b"\xa5" * 512


def test_read_part_data_pads_short_payload_with_ff(tmp_path):
    """A partition whose declared size exceeds its payload is padded to size with
    0xFF, so the device is always handed exactly part_size bytes."""
    parts = [Partition("padded", offset=0, data=b"\xa5" * 100, size=256)]
    img = write_kdimg_file(tmp_path / "padded.kdimg", parts)
    kdimg = KburnKdImage(img)
    items = kdimg.items()

    data = kdimg.read_part_data(items.data[0])

    assert len(data) == 256
    assert data[:100] == b"\xa5" * 100
    assert data[100:] == b"\xff" * 156


def test_max_offset_reports_end_of_last_partition(tmp_path):
    """handle_uboot_mode compares this against the device capacity before
    writing, so an understated value would let an oversized image through."""
    parts = [
        Partition("a", offset=0, data=b"\x00" * 16, size=16, max_size=0x1000),
        Partition("b", offset=0x10000, data=b"\x00" * 16, size=16, max_size=0x2000),
    ]
    img = write_kdimg_file(tmp_path / "offsets.kdimg", parts)

    assert get_kdimage_max_offset(img) == 0x10000 + 0x2000


# --- integrity checks ---------------------------------------------------------


def test_rejects_bad_header_magic(tmp_path, two_partitions):
    img = tmp_path / "bad_magic.kdimg"
    img.write_bytes(build_kdimg(two_partitions, header_magic=0xDEADBEEF))

    assert get_kdimage_items(img) is None


def test_rejects_bad_header_crc(tmp_path, two_partitions):
    img = tmp_path / "bad_hdr_crc.kdimg"
    img.write_bytes(build_kdimg(two_partitions, corrupt_header_crc=True))

    assert get_kdimage_items(img) is None


def test_rejects_bad_partition_table_crc(tmp_path, two_partitions):
    img = tmp_path / "bad_tbl_crc.kdimg"
    img.write_bytes(build_kdimg(two_partitions, corrupt_table_crc=True))

    assert get_kdimage_items(img) is None


def test_read_part_data_rejects_sha_mismatch(tmp_path, two_partitions):
    """The container parses fine; only the payload hash is wrong. Silently
    flashing a partition whose contents do not match its recorded digest would
    brick a board, so this must fail rather than return the bytes.

    It raises rather than returning None so the caller can tell a digest
    mismatch apart from an unreadable file; both used to collapse into None.
    """
    img = tmp_path / "bad_sha.kdimg"
    img.write_bytes(build_kdimg(two_partitions, corrupt_sha_of="uboot_spl_a"))

    kdimg = KburnKdImage(img)
    items = kdimg.items()
    assert items is not None, "structure is intact; only the payload digest is wrong"

    with pytest.raises(KdimageError) as exc:
        kdimg.read_part_data(items.data[0])

    assert "uboot_spl_a" in str(exc.value)


def test_sha_is_computed_over_unpadded_payload(tmp_path):
    """Guards the padding/verify ordering: the digest covers the stored payload,
    and padding happens afterwards. Verifying post-padding would reject every
    short partition."""
    payload = b"\xa5" * 100
    parts = [Partition("padded", offset=0, data=payload, size=256)]
    img = write_kdimg_file(tmp_path / "padded_sha.kdimg", parts)
    kdimg = KburnKdImage(img)
    items = kdimg.items()

    assert items.data[0].expectedSha256 == hashlib.sha256(payload).hexdigest()
    assert kdimg.read_part_data(items.data[0]) is not None
